Daily bet functionality
danilobassi8/prode pull request #5
Opened 2022-10-23 19:08 UTC by SebastianMoreyraUTN

### List of matches ẁith user bets and bet creation
Added the minimum functionality to save user bets. There is a lot of work left in terms of styling and design. This PR is to have  a starting point for further development of this functionality.

![image](https://user-images.githubusercontent.com/64164685/197411118-3779d40a-cd8a-41c0-a257-4dc2c56c6ea8.png)

2022-10-24 21:30 UTC, danilobassi8 commented on src/app/components/daily-bet/daily-bet.component.html
> +        <span> {{ match?.home_team?.name }} </span>
I'll add a text like 'TBD' for matches with no team.

2022-10-24 21:34 UTC, danilobassi8 commented on src/app/services/world-cup.service.ts
> +  getTeamFlagById(id: number) {
I remember giving you this function to get flags but with the other styled flags, please change this function name to "getTeamBigFlags", so it doesn't interfere with my previous bet flags.

2022-10-25 11:41 UTC, srenzi commented on src/app/components/daily-bet/daily-bet.component.html
> +        <span> {{ match?.home_team?.name }} </span>
I would use 'A definir'. Sounds better in Spanish than TBD.

2022-10-25 17:14 UTC, danilobassi8 approved these changes

2022-10-25 23:18 UTC, srenzi requested changes
All my comments can be addressed in a separate PR. I made comments based on what I see so that we don't forget.

2022-10-25 23:18 UTC, srenzi commented on src/app/services/world-cup.service.ts
> +  LAST_16: 'Octavos',
Please rename to "Octavos de final"

2022-10-25 23:18 UTC, srenzi commented on src/app/services/world-cup.service.ts
> +  QUARTER_FINALS: 'Cuartos',
Please rename to "Cuartos de final"

2022-10-25 23:18 UTC, srenzi commented on src/app/components/daily-bet/daily-bet.component.html
> +      >{{ match?.date }} - [Cuanto falta | En curso | Finalizado]</span
Here we should format the date and time to a more friendly format, such as _28-11-2022 13:00_

This means changing:
1- Date format should be dd-MM-yyyy instead of the current yyyy-MM-dd
2- Time should only have hours and minutes
3- Time is stored in GMT. It should be transformed using the browser time to local time

2022-10-25 23:18 UTC, srenzi commented on src/app/components/daily-bet/daily-bet.component.html
> +    ></button>
We should probably add a button here to show other people's bets which will be hidden and only shown after bets are over. So it will replace the current "Guardar Pronóstico"

2022-10-25 23:18 UTC, srenzi commented on src/app/components/layout/layout.component.ts
> +        label: 'Cerrar Sesión',
We may want to show the current user name + last name here and have the "Cerrar sesión" option in a dropdown menu

2022-10-27 17:58 UTC, SebastianMoreyraUTN commented on src/app/components/daily-bet/daily-bet.component.html
> +      >{{ match?.date }} - [Cuanto falta | En curso | Finalizado]</span
Will be changed in future PRs

2022-10-27 18:01 UTC, SebastianMoreyraUTN commented on src/app/components/layout/layout.component.ts
> +        label: 'Cerrar Sesión',
Great, I will do it in the next sprint

2022-10-27 18:01 UTC, SebastianMoreyraUTN commented on src/app/components/daily-bet/daily-bet.component.html
> +    ></button>
Next sprint

2022-10-27 18:01 UTC, SebastianMoreyraUTN commented on src/app/services/world-cup.service.ts
> +  QUARTER_FINALS: 'Cuartos',
Done

2022-10-27 19:28 UTC, merged